# Generated by Django 6.0.3 on 2026-04-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etllog',
            new_name='analytics_e_pipelin_6d9c1b_idx',
            old_name='analytics_e_pipelin_idx',
        ),
        migrations.RenameIndex(
            model_name='etllog',
            new_name='analytics_e_dataset_17d9b6_idx',
            old_name='analytics_e_dataset_idx',
        ),
        migrations.RenameIndex(
            model_name='modelmetric',
            new_name='analytics_m_maladie_8b8a79_idx',
            old_name='analytics_m_maladie_idx',
        ),
    ]
