# Generated by Django 6.0.3 on 2026-04-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icone_svg', models.TextField()),
                ('condition_type', models.CharField(choices=[('premier_exo', 'Premier exercice'), ('streak', 'Série de jours consécutifs'), ('score_parfait', 'Score parfait'), ('nb_tentatives', 'Nombre de tentatives'), ('nb_maladies', 'Nombre de maladies explorées')], max_length=30)),
                ('condition_seuil', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='badges.badge')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('etudiant', 'badge')},
            },
        ),
    ]
