# Generated by Django 6.0.3 on 2026-04-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('chemin_fichier', models.CharField(max_length=500)),
                ('accuracy', models.FloatField()),
                ('mlflow_run_id', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=False)),
                ('date_entrainement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
